import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { getSavedLanguage, saveLanguage } from '@/database/appstate';

type Language = 'en' | 'es';

type TranslationKey = keyof typeof translations.en;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const translations = {
  en: {
    choose_language_title: 'Please choose a language',
    english: 'English',
    spanish: 'Spanish',
    continue: 'Continue',
    business_title_new: 'Please enter your company details',
    business_title_edit: 'Edit your company details',
    business_name: 'Company Name',
    business_email: 'Company Email',
    business_phone: 'Phone Number',
    business_address: 'Address',
    business_industry: 'Industry',
    business_photo_upload: 'Upload Business Photo (Optional)',
    business_photo_change: 'Change Business Photo',
    business_photo_remove: 'Remove Photo',
    business_save_info: 'Save Info',
    business_save_changes: 'Save Changes',
    business_loading: 'Loading...',
    business_missing_name: 'Please enter your company name.',
    business_missing_email: 'Please enter your company email.',
    business_invalid_phone: 'Please enter a valid phone number.',
    business_missing_address: 'Please enter your company address.',
    business_missing_industry: 'Please enter your company industry.',
    business_save_failed: 'Could not save business info.',
    business_permission_needed: 'Permission needed',
    business_permission_message: 'Please allow photo library access to choose a logo.',
    business_index: 'Loading...',
    business_cant_load: 'Could not load business info.',
    business_info: 'Business Info',
    business_info_not_saved: 'No business information saved yet.',
    add_product: 'Add Product',
    no_products: 'No Products yet',
    invoice_client_missing: 'Missing cleint, Please enter a client name.',
    invoice_number_invalid: 'Invalid invoice number, Please enter a valid number.',
    invoice_date_invalid: 'Invalid invoice date, Please enter a valid date.',
    invoice_total_invalid: 'Invalid total, Please enter a valid total.',
    invoice_saved: 'Invovice Saved',
    invoice_fail_save: 'Invoice did not save properly, Could not save the invoice',
    invoice_no_pdf: 'No Invoice, Generate Invoice first.',
    invoice_no_save_pdf: 'Saved failed, Could not save Invoice',
    invoice_shared_failed: 'Share failed, Sharing is not available on this device',
    invoice_print_failed: ' Print failed, Could not print the Invoice',
    invoice_pdf_failed_title: 'PDF failed',
    invoice_pdf_failed_message: 'Could not generate the invoice PDF.',
    invoice_no_pdf_yet_title: 'No PDF yet',
    invoice_generate_pdf_first: 'Generate the PDF first.',
    invoice_saved_title: 'Saved',
    invoice_pdf_saved_folder: 'PDF saved to invoices folder',
    invoice_save_failed_title: 'Save failed',
    invoice_pdf_save_failed_message: 'Could not save the PDF.',
    invoice_sharing_not_available_title: 'Sharing not available',
    invoice_sharing_not_available_message: 'Sharing is not available on this device.',
    invoice_preview_title: 'Invoice Preview',
    close: 'Close',
    client_label: 'Client',
    date_label: 'Date',
    subtotal_label: 'Subtotal',
    tax_label: 'Tax',
    discount_label: 'Discount',
    total_label: 'Total',
    invoice_pdf_ready_share_print: 'PDF generated and ready to share or print',
    save_pdf: 'Save PDF',
    share: 'Share',
    print: 'Print',
    back_to_edit: 'Back to Edit',
    done: 'Done',
    edit_invoice: 'Edit Invoice',
    new_invoice: 'New Invoice',
    logo_position: 'Logo position',
    top_center: 'Top center',
    top_left: 'Top left',
    no_logo_saved: 'No logo saved',
    client_name_placeholder: 'Client name',
    invoice_number_placeholder: 'Invoice number',
    invoice_date_placeholder: 'Invoice date (MM/DD/YYYY)',
    select_products: 'Select products',
    item_label: 'Item',
    manual_label: 'Manual',
    qty_label: 'Qty',
    subtotal_calculated_placeholder: 'Subtotal (calculated)',
    tax_percent_placeholder: 'Tax (%)',
    discount_percent_placeholder: 'Discount (%)',
    details_placeholder: 'Details',
    notes_placeholder: 'Notes',
    terms_and_conditions_placeholder: 'Terms and conditions',
    generate_pdf: 'Generate PDF',
    save_invoice: 'Save Invoice',
    no_products_saved_yet: 'No products saved yet.',
    selected: 'Selected',
    select: 'Select',
    use_manual_amount: 'Use manual amount',
    auto: 'Auto',
    manual_amount: 'Manual amount',
    unit_price: 'Unit price',
    pdf_ready_to_export: 'PDF ready to export.',
    import: 'Import',
    add: 'Add',
    no_customers_yet: 'No customers yet.',
    no_companies_found: 'No companies found.',
    customer_singular: 'customer',
    customer_plural: 'customers',
    company_associates: 'Company Associates',
    no_associates_found: 'No associates found.',
    customer_jobs: 'Customer Jobs',
    no_jobs_yet: 'No jobs yet.',
    invoice_label: 'Invoice',
    completed: 'Completed',
    pending: 'Pending',
    documents: 'Documents',
    no_documents_yet: 'No documents yet.',
    business_analytics: 'Business Analytics',
    tab_estimates: 'Estimates',
    tab_pending: 'Pending',
    tab_revenue: 'Revenue',
    tab_customers: 'Customers',
    tab_invoices: 'Invoices',
    new_estimate: 'New Estimate',
    no_estimates_created: 'No Estimates have been created',
    delete_estimate_title: 'Delete estimate',
    delete_estimate_message: 'Delete estimate #{{number}}?',
    mark_as_won_title: 'Mark as won',
    convert_estimate_message: 'Convert estimate #{{number}} to an invoice?',
    convert_estimate_title: 'Convert estimate',
    convert: 'Convert',
    new: 'New',
    no_invoices_yet: 'No invoices yet.',
    delete_invoice_title: 'Delete invoice',
    delete_invoice_message: 'Delete invoice #{{number}}?',
    cancel: 'Cancel',
    delete: 'Delete',
    no_employees_yet: 'No employees yet',
    add_first_employee: 'Add your first employee to get started.',
    no_results: 'No results',
    no_employees_search_match: 'We couldn\'t find any employees matching that search.',
    no_matches: 'No matches',
    no_employees_filter_match: 'No employees match those filters.',


  },
  es: {
    choose_language_title: 'Por favor, elija un idioma',
    english: 'Ingles',
    spanish: 'Espanol',
    continue: 'Continuar',
    business_title_new: 'Por favor ingrese los datos de su empresa',
    business_title_edit: 'Editar los datos de su empresa',
    business_name: 'Nombre de la empresa',
    business_email: 'Correo de la empresa',
    business_phone: 'Numero de telefono',
    business_address: 'Direccion',
    business_industry: 'Industria',
    business_photo_upload: 'Subir foto de la empresa (Opcional)',
    business_photo_change: 'Cambiar foto de la empresa',
    business_photo_remove: 'Eliminar foto',
    business_save_info: 'Guardar',
    business_save_changes: 'Guardar cambios',
    business_loading: 'Cargando...',
    business_missing_name: 'Por favor ingrese el nombre de la empresa.',
    business_missing_email: 'Por favor ingrese el correo de la empresa.',
    business_invalid_phone: 'Por favor ingrese un numero de telefono valido.',
    business_missing_address: 'Por favor ingrese la direccion de la empresa.',
    business_missing_industry: 'Por favor ingrese la industria de la empresa.',
    business_save_failed: 'No se pudo guardar la informacion.',
    business_permission_needed: 'Se necesita permiso',
    business_permission_message: 'Permita acceso a la galeria para elegir un logo.',
    business_index: 'Cargando...',
    business_cant_load: 'No se pudo cargar la informacion de la empresa.',
    business_info: 'Informacion de la empresa',
    business_info_not_saved: 'No hay informacion de la empresa guardada.',
    add_product: 'Agregar producto',
    no_products: 'No hay productos aun',
    invoice_client_missing: 'Falta el clientes nombre, por favor ingrese un nombre de cliente.',
    invoice_number_invalid: 'Numero de factura invalido, Por favor ingrese un numero valido.',
    invoice_date_invalid: 'Fecha de factura invalida, Por favor ingrese una fecha valida.',
    invoice_total_invalid: 'Total invalido, Por favor ingrese un total valido.',
    invoice_saved: 'Invoice Guardado',
    invoice_fail_save: 'Invoice no se guardo, No se pudo guardar el Invoice.',
    invoice_no_pdf: 'No PDF, Generar el Invoice primero.',
    invoice_no_save_pdf: 'Error al guardar, No se pudo guardar el Invoice',
    invoice_shared_failed: 'Error al compartir, No se pudo compatir el Invoice',
    invoice_print_failed: 'Imprimir fallo, No se Pudo Iimprimir el Invoice',
    invoice_pdf_failed_title: 'Error de PDF',
    invoice_pdf_failed_message: 'No se pudo generar el PDF de la factura.',
    invoice_no_pdf_yet_title: 'Aun no hay PDF',
    invoice_generate_pdf_first: 'Genere el PDF primero.',
    invoice_saved_title: 'Guardado',
    invoice_pdf_saved_folder: 'PDF guardado en la carpeta de facturas',
    invoice_save_failed_title: 'Error al guardar',
    invoice_pdf_save_failed_message: 'No se pudo guardar el PDF.',
    invoice_sharing_not_available_title: 'Compartir no disponible',
    invoice_sharing_not_available_message: 'Compartir no esta disponible en este dispositivo.',
    invoice_preview_title: 'Vista previa de factura',
    close: 'Cerrar',
    client_label: 'Cliente',
    date_label: 'Fecha',
    subtotal_label: 'Subtotal',
    tax_label: 'Impuesto',
    discount_label: 'Descuento',
    total_label: 'Total',
    invoice_pdf_ready_share_print: 'PDF generado y listo para compartir o imprimir',
    save_pdf: 'Guardar PDF',
    share: 'Compartir',
    print: 'Imprimir',
    back_to_edit: 'Volver a editar',
    done: 'Listo',
    edit_invoice: 'Editar factura',
    new_invoice: 'Nueva factura',
    logo_position: 'Posicion del logo',
    top_center: 'Arriba al centro',
    top_left: 'Arriba a la izquierda',
    no_logo_saved: 'No hay logo guardado',
    client_name_placeholder: 'Nombre del cliente',
    invoice_number_placeholder: 'Numero de factura',
    invoice_date_placeholder: 'Fecha de factura (MM/DD/YYYY)',
    select_products: 'Seleccionar productos',
    item_label: 'Articulo',
    manual_label: 'Manual',
    qty_label: 'Cant.',
    subtotal_calculated_placeholder: 'Subtotal (calculado)',
    tax_percent_placeholder: 'Impuesto (%)',
    discount_percent_placeholder: 'Descuento (%)',
    details_placeholder: 'Detalles',
    notes_placeholder: 'Notas',
    terms_and_conditions_placeholder: 'Terminos y condiciones',
    generate_pdf: 'Generar PDF',
    save_invoice: 'Guardar factura',
    no_products_saved_yet: 'No hay productos guardados aun.',
    selected: 'Seleccionado',
    select: 'Seleccionar',
    use_manual_amount: 'Usar monto manual',
    auto: 'Auto',
    manual_amount: 'Monto manual',
    unit_price: 'Precio unitario',
    pdf_ready_to_export: 'PDF listo para exportar.'
    ,
    import: 'Importar',
    add: 'Agregar',
    no_customers_yet: 'No hay clientes aun.',
    no_companies_found: 'No se encontraron empresas.',
    customer_singular: 'cliente',
    customer_plural: 'clientes',
    company_associates: 'Asociados de la empresa',
    no_associates_found: 'No se encontraron asociados.',
    customer_jobs: 'Trabajos del cliente',
    no_jobs_yet: 'No hay trabajos aun.',
    invoice_label: 'Factura',
    completed: 'Completado',
    pending: 'Pendiente',
    documents: 'Documentos',
    no_documents_yet: 'No hay documentos aun.',
    business_analytics: 'Analisis del negocio',
    tab_estimates: 'Estimados',
    tab_pending: 'Pendientes',
    tab_revenue: 'Ingresos',
    tab_customers: 'Clientes',
    tab_invoices: 'Facturas',
    new_estimate: 'Nuevo estimado',
    no_estimates_created: 'No se han creado estimados',
    delete_estimate_title: 'Eliminar estimado',
    delete_estimate_message: 'Eliminar estimado #{{number}}?',
    mark_as_won_title: 'Marcar como ganado',
    convert_estimate_message: 'Convertir estimado #{{number}} a factura?',
    convert_estimate_title: 'Convertir estimado',
    convert: 'Convertir',
    new: 'Nuevo',
    no_invoices_yet: 'No hay facturas aun.',
    delete_invoice_title: 'Eliminar factura',
    delete_invoice_message: 'Eliminar factura #{{number}}?',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    no_employees_yet: 'No hay empleados aun',
    add_first_employee: 'Agregue su primer empleado para comenzar.',
    no_results: 'Sin resultados',
    no_employees_search_match: 'No encontramos empleados que coincidan con esa busqueda.',
    no_matches: 'Sin coincidencias',
    no_employees_filter_match: 'No hay empleados que coincidan con esos filtros.'

  },
} as const;

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const loadLanguage = async () => {
      const saved = await getSavedLanguage();
      if (saved) {
        setLanguageState(saved);
      }
    };

    loadLanguage();
  }, []);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    void saveLanguage(nextLanguage);
  };

  const value = useMemo<LanguageContextValue>(() => {
    return {
      language,
      setLanguage,
      t: (key: TranslationKey) => translations[language][key],
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
};
